### ISSUE TITLE
Error in code on page 470

### ISSUE THREAD

**Issue by cmgustin** [spbooks/jsninja2#1]
On page 470, in the example for adding methods to the Number prototype, the code to add the functions is correct:
`Number.prototype.isEven = function() {
  return this%2 === 0;
}
Number.prototype.isOdd = function() {
  return this%2 === 1;
}`

However the code in the next block showing how to invoke the newly added functions on numbers will throw a syntax error (tested in JSBin and node console via Terminal). The book has:
`42.isEven() << true
765234.isOdd() << false` 

Since the method is being called on an integer, there should be two dots:
`42..isEven() << true
765234..isOdd() << false`

Anyhow, loving the book, but this threw me off so I wanted to post an issue here for future revisions/releases, or in case this trips up anyone else.

Also, if there's a better place to post this, let me know and I'll be happy to revise or resubmit.

**Comment by simonmackie** [comment]
Hi Chris,

Thanks for the heads-up. We'll get that fixed in a future update.

**Comment by daz4126** [comment]
Hi Chris,

Good spot! Thanks for sending it in.

Glad you're enjoying the book!

**Comment by simonmackie** [comment]
We've just fixed this in the May 2018 update, thanks Chris.
