### ISSUE TITLE
Likely typos on pages 614, 618 and 619

### ISSUE THREAD

**Issue by JLammeer** [spbooks/jsninja2#13]
Isn't it supposed to be "bundle.js", at these pages?

---

**Page 614:**
![17](https://user-images.githubusercontent.com/35262827/42524256-5bb1c302-8446-11e8-9d27-e2642b766314.png)

---

**Page 618:**
![18](https://user-images.githubusercontent.com/35262827/42524434-d4753a6c-8446-11e8-9780-390c9a7286b2.png)

---

**Page 619:**
![19](https://user-images.githubusercontent.com/35262827/42524452-e472bf7a-8446-11e8-9f51-579f4cd69706.png)

**Comment by simonmackie** [comment]
Yes! How odd. Maybe a find/replace that went wrong. Anyway, fixed in the August update, thanks.
