### ISSUE TITLE
Outdated url on page 534

### ISSUE THREAD

**Issue by JLammeer** [spbooks/jsninja2#20]
This URL is not working.

---

![14](https://user-images.githubusercontent.com/35262827/42523764-17e81442-8445-11e8-9f74-1f4ab2aab5e2.png)

**Comment by JLammeer** [comment]
Hence, the Ninja Quiz page.

**Comment by simonmackie** [comment]
This has now been fixed in the August update, something else broke it (updated URL is: https://spbooks.github.io/jsninja2/questions.json)
