### ISSUE TITLE
Missing view.render on page 571

### ISSUE THREAD

**Issue by JLammeer** [spbooks/jsninja2#22]
Second code block **is missing view.render**, hence it does not work or match the [repo](https://github.com/spbooks/jsninja2/blob/master/Ch%2014/quiz/main.js).

---

![16](https://user-images.githubusercontent.com/35262827/42524126-f4deaf8c-8445-11e8-93b5-e5fa2c628aec.png)

**Comment by simonmackie** [comment]
Fixed in August update, thanks!
