### ISSUE TITLE
Wrong formatting, maybe?

### ISSUE THREAD

**Issue by JLammeer** [spbooks/jsninja2#25]
**Page 637:**
![22](https://user-images.githubusercontent.com/35262827/42524678-a0e7bff2-8447-11e8-81ee-19aba1ee2760.png)

---

**Page 644:**
![23](https://user-images.githubusercontent.com/35262827/42524893-2bc45928-8448-11e8-92f9-11e770bbcaf6.png)

**Comment by simonmackie** [comment]
Fixed in the August update, thanks
