### ISSUE TITLE
Missing online code

### ISSUE THREAD

**Issue by gandalf458** [spbooks/jsninja2#28]
On page 534, the exercise needs access to
http://spbooks.github.io/questions.json
but this gives a 404.

The answer I was given that the code is in the code archive isn't helpful since it needs to be online somewhere to use JSON fetch().

**Comment by simonmackie** [comment]
Something has broken the link. In the meantime, I've put the file at https://spbooks.github.io/jsninja2/questions.json.

**Comment by simonmackie** [comment]
This has now been fixed in the August update, something else broke it (updated URL is: https://spbooks.github.io/jsninja2/questions.json)
