### ISSUE TITLE
Bracket instead of Parenthesis

### ISSUE THREAD

**Issue by NekCS** [spbooks/jsninja2#4]
I think that there is a small mistake on pg 168
const ironMan = **(** name: name, realName: realName };
should be
const ironMan = **{** name: name, realName: realName };

Please let me know if this the right way to point mistakes or if I should email you.

**Comment by simonmackie** [comment]
Here is fine Nektarios. We'll correct it in a future update.

**Comment by simonmackie** [comment]
Fixed in the August update
